before_script:
  - mysql -e 'create database alonetone_test';
  - rake copy_config
notifications:
  email:
    on_success: [always|never|change] # default: change
    on_failure: [always|never|change] # default: change