---
development: &defaults
  show_debug_info: true
  app_name: YourAppName
  url: yourapp.com
  email: support@yourapp.com
  secret: f041541efd6d104c7051041ec61e7aa5
  storage: filesystem
  bucket: 
  amazon_id: 
  amazon_key:
  rakismet_key:
  defensio:  
  campfire_url: nil
  video_size: width="370" height="308"
  enable_defensio: false
  ga: 
  get_clicky: 
  typekit: 

test:
  <<: *defaults
  storage: filesystem
  show_debug_info: false

production:
  <<: *defaults
  show_debug_info: false
  enable_defensio: true
  campfire_url: yourapp.campfirenow.com/chat

