---
development: &defaults
  show_debug_info: true
  app_name: YourAppName
  url: yourapp.com
  email: support@yourapp.com
  secret: yourappsecret
  storage: s3
  bucket: mp3.yourapp.com
  amazon_id: s3id12341234 
  amazon_key: s3key12341234
  campfire_url: nil
  video_size: width="370" height="308"
  enable_defensio: false
  ga: YOUR-GOOGLE-ANAYTICS-ID
  get_clicky: getclickyid
  typekit: typekitid

test:
  <<: *defaults
  show_debug_info: false

production:
  <<: *defaults
  show_debug_info: false
  enable_defensio: true
  campfire_url: yourapp.campfirenow.com/chat

