---
development: &defaults
  show_debug_info: false
  video_size: width="370" height="308"
  storage: file_system
  path_prefix: public/
  site_url: dev.alonetone.com

test:
  <<: *defaults
  show_debug_info: true

production:
  <<: *defaults
  storage: s3
  path_prefix: ""
  site_url: alonetone.com