development:
  api_key: 8504ef1f078874a537372f17dc178af3
  owner_url: alonetone.com

test:
  api_key: 8504ef1f078874a537372f17dc178af3
  owner_url: http://code.macournoyer.com/svn/plugins/defensio

production:
  api_key: 8504ef1f078874a537372f17dc178af3
  owner_url: alonetone.com