--- 
port: 5000
servers: 3
docroot: public    
environment: production 
cwd: /data/alonetone/current
log_file: /var/log/engineyard/mongrel/alonetone/mongrel.log
pid_file: /var/run/mongrel/alonetone/mongrel.pid
user: alonetone
group: alonetone



